import colors from "ansi-colors";

export const symbols = {
  tick: "✔",
  info: "ℹ",
  warning: "⚠",
  cross: "✘",
  squareSmall: "◻",
  squareSmallFilled: "◼",
  circle: "◯",
  circleFilled: "◉",
  circleDotted: "◌",
  circleDouble: "◎",
  circleCircle: "ⓞ",
  circleCross: "ⓧ",
  circlePipe: "Ⓘ",
  radioOn: "◉",
  radioOff: "◯",
  checkboxOn: "☒",
  checkboxOff: "☐",
  checkboxCircleOn: "ⓧ",
  checkboxCircleOff: "Ⓘ",
  pointer: "❯",
  triangleUpOutline: "△",
  triangleLeft: "◀",
  triangleRight: "▶",
  triangleLeftOutlined: "◁",
  triangleRightOutlined: "▷",
  lozenge: "◆",
  lozengeOutline: "◇",
  hamburger: "☰",
  smiley: "㋡",
  mustache: "෴",
  star: "★",
  play: "▶",
  nodejs: "⬢",
  oneSeventh: "⅐",
  oneNinth: "⅑",
  oneTenth: "⅒",
  fullHeightBar: "│",
};

export const coloredSymbols = {
  tick: colors.green("✔"),
  info: colors.yellow("▶"),
  warning: colors.red.bold("⚠"),
  cross: colors.red.bold("✘"),
  stepPrefix: "┌",
  stepInfo: "◇",
  stepGap: "│",
  stepActive: colors.cyan("◇"),
  stepSuccess: colors.green("◆"),
  stepDone: colors.green("✔"),
  stepSuffix: "└",
};
